# DB
db_host='localhost'
db_name='news'
db_user='root'
db_password=''
# Base client
base_uri="http://localhost"
timeout= 2.0
verify= false
# URLs
proxy = "localhost:8888"
is_avaible_url = "/health"
send_message_url = "/messages/sendToAll"